### PR TITLE
Recover from unexpected EOF with API Server

### LINKED ISSUE #53: Operator crashes constantly  on Azure AKS
I am trying to deploy NATS using NATS Operator on a 3 Node Kubernetes (v. 1.9.6) cluster on Azure, following this projects readme.md. While the NATS pods appear being fine, the operator is in a never ending crash/restart loop.

The k8s resources and logs of the NATS pods are listed below. At the very end of the operators log an error and a fatal entry are the last things that are logged before the operator goes down.

```
PS C:\src\aks_test> kubectl get all -o wide
NAME                                 READY     STATUS             RESTARTS   AGE       IP           NODE
pod/example-nats-cluster-1           1/1       Running            0          24m       10.244.2.5   aks-nodepool1-32539510-1
pod/example-nats-cluster-2           1/1       Running            0          23m       10.244.1.5   aks-nodepool1-32539510-2
pod/example-nats-cluster-3           1/1       Running            0          23m       10.244.0.4   aks-nodepool1-32539510-0
pod/nats-operator-7fdf945577-jxg5s   0/1       CrashLoopBackOff   7          24m       10.244.1.4   aks-nodepool1-32539510-2

NAME                                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE       SELECTOR
service/example-nats-cluster        ClusterIP   10.0.5.144   <none>        4222/TCP            24m       app=nats,nats_cluster=example-nats-cluster
service/example-nats-cluster-mgmt   ClusterIP   None         <none>        6222/TCP,8222/TCP   24m       app=nats,nats_cluster=example-nats-cluster,nats_version=1.1.0
service/kubernetes                  ClusterIP   10.0.0.1     <none>        443/TCP             30m       <none>

NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS      IMAGES                                           SELECTOR
deployment.extensions/nats-operator   1         1         1            0           24m       nats-operator   connecteverything/nats-operator:0.2.2-v1alpha2   name=nats-operator

NAME                                             DESIRED   CURRENT   READY     AGE       CONTAINERS      IMAGES                                           SELECTOR
replicaset.extensions/nats-operator-7fdf945577   1         1         0         24m       nats-operator   connecteverything/nats-operator:0.2.2-v1alpha2   name=nats-operator,pod-
template-hash=3989501133

NAME                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS      IMAGES                                           SELECTOR
deployment.apps/nats-operator   1         1         1            0           24m       nats-operator   connecteverything/nats-operator:0.2.2-v1alpha2   name=nats-operator

NAME                                       DESIRED   CURRENT   READY     AGE       CONTAINERS      IMAGES                                           SELECTOR
replicaset.apps/nats-operator-7fdf945577   1         1         0         24m       nats-operator   connecteverything/nats-operator:0.2.2-v1alpha2   name=nats-operator,pod-templa
te-hash=3989501133
PS C:\src\aks_test> kubectl logs example-nats-cluster-1
[1] 2018/06/24 07:57:54.986814 [INF] Starting nats-server version 1.1.0
[1] 2018/06/24 07:57:54.986911 [INF] Git commit [add6d79]
[1] 2018/06/24 07:57:54.987207 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2018/06/24 07:57:54.987305 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/06/24 07:57:54.987370 [INF] Server is ready
[1] 2018/06/24 07:57:54.987877 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2018/06/24 07:58:00.347433 [INF] 10.244.1.5:52728 - rid:1 - Route connection created
[1] 2018/06/24 07:58:07.904174 [INF] 10.244.0.4:60902 - rid:2 - Route connection created
PS C:\src\aks_test> kubectl logs example-nats-cluster-2
[1] 2018/06/24 07:58:00.328032 [INF] Starting nats-server version 1.1.0
[1] 2018/06/24 07:58:00.328063 [INF] Git commit [add6d79]
[1] 2018/06/24 07:58:00.328240 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2018/06/24 07:58:00.328276 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/06/24 07:58:00.328286 [INF] Server is ready
[1] 2018/06/24 07:58:00.328526 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2018/06/24 07:58:00.336456 [INF] 10.244.2.5:6222 - rid:1 - Route connection created
[1] 2018/06/24 07:58:00.373683 [ERR] Error trying to connect to route: dial tcp: lookup example-nats-cluster-2.example-nats-cluster-mgmt.default.svc on 10.0.0.10:53: no such hos
t
[1] 2018/06/24 07:58:01.377851 [INF] 10.244.1.5:43288 - rid:2 - Route connection created
[1] 2018/06/24 07:58:01.378108 [INF] 10.244.1.5:6222 - rid:3 - Route connection created
[1] 2018/06/24 07:58:07.893824 [INF] 10.244.0.4:60642 - rid:4 - Route connection created
PS C:\src\aks_test> kubectl logs example-nats-cluster-3
[1] 2018/06/24 07:58:07.882819 [INF] Starting nats-server version 1.1.0
[1] 2018/06/24 07:58:07.882851 [INF] Git commit [add6d79]
[1] 2018/06/24 07:58:07.883013 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2018/06/24 07:58:07.883045 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/06/24 07:58:07.883055 [INF] Server is ready
[1] 2018/06/24 07:58:07.883346 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2018/06/24 07:58:07.893434 [INF] 10.244.2.5:6222 - rid:1 - Route connection created
[1] 2018/06/24 07:58:07.893807 [INF] 10.244.1.5:6222 - rid:2 - Route connection created
[1] 2018/06/24 07:58:07.901949 [ERR] Error trying to connect to route: dial tcp: lookup example-nats-cluster-3.example-nats-cluster-mgmt.default.svc on 10.0.0.10:53: no such hos
t
[1] 2018/06/24 07:58:08.906155 [INF] 10.244.0.4:6222 - rid:3 - Route connection created
[1] 2018/06/24 07:58:08.906461 [INF] 10.244.0.4:36868 - rid:4 - Route connection created
PS C:\src\aks_test> kubectl logs -f nats-operator-7fdf945577-jxg5s
time="2018-06-24T08:22:07Z" level=info msg="nats-operator Version: 0.2.2-v1alpha2+git"
time="2018-06-24T08:22:07Z" level=info msg="Git SHA: fb2847b"
time="2018-06-24T08:22:07Z" level=info msg="Go Version: go1.9"
time="2018-06-24T08:22:07Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-06-24T08:22:08Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"default\", Name:\"nats-operator\", UID:\"3902fb5a-7784-11e8-b0cb-0a58ac1f054
6\", APIVersion:\"v1\", ResourceVersion:\"3266\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' nats-operator-7fdf945577-jxg5s became leader"
time="2018-06-24T08:22:08Z" level=info msg="finding existing clusters..." pkg=controller
time="2018-06-24T08:22:08Z" level=info msg="starts running from watch version: 3270" pkg=controller
time="2018-06-24T08:22:08Z" level=info msg="start running..." cluster-name=example-nats-cluster pkg=cluster
time="2018-06-24T08:22:08Z" level=info msg="start watching at 3270" pkg=controller
time="2018-06-24T08:23:08Z" level=error msg="received invalid event from API server: fail to decode raw event from apiserver (unexpected EOF)" pkg=controller
time="2018-06-24T08:23:08Z" level=fatal msg="controller Run() ended with failure: fail to decode raw event from apiserver (unexpected EOF)"
```

### Full repro:
**Prerequisites:**
* Azure Subscription (the free trial is sufficient)
* Azure CLI installed (see https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) or run browser based Azure Cloud shell from portal.azure.com

```
$ az login
$ az provider register -n Microsoft.Network
$ az provider register -n Microsoft.Storage
$ az provider register -n Microsoft.Compute
$ az provider register -n Microsoft.ContainerService
$ az group create --name aks --location westeurope
$ az aks create --resource-group aks --name aksCluster --node-count 3 --generate-ssh-keys #Create k8s cluster with 3 nodes, this will take 10 to 15 minutes
$ az aks install-cli #Install kubectl, may not be necessary if already installed or if running Azure Cloud Shell
$ az aks get-credentials --resource-group aks --name aksCluster #Setup kubectl to connect to our Azure k8s cluster
$ kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-operator/88f19bcd7da571a3004c364859ebbce3202c510e/example/deployment.yaml
$ echo '
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "example-nats-cluster"
spec:
  size: 3
  version: "1.1.0"
' | kubectl apply -f -

$ az group delete --name aks --yes --no-wait #Delete everything once you don't need the cluster anymore
```

### PR DESCRIPTION
**Pull request by wallyqs**
Fixes #53 

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

File: pkg/controller/util.go [hunk 1]
```diff
@@ -35,9 +35,10 @@ func pollEvent(decoder *json.Decoder) (*Event, *metav1.Status, error) {
 	re := &rawEvent{}
 	err := decoder.Decode(re)
 	if err != nil {
-		if err == io.EOF {
+		if err == io.EOF || err == io.ErrUnexpectedEOF {
```
Comment (wallyqs) [inline pkg/controller/util.go]: here could also be a GoAwayError from http2 
```
received invalid event from API server: fail to decode raw event from apiserver (http2: server sent GOAWAY and closed the connection; LastStreamID=2475, ErrCode=NO_ERROR, debug="") 
```
