### PR TITLE
controller: delete pods in terminal state

### LINKED ISSUE #104: Unable to recover from node crash
I was testing this locally until the node crashed (minikube). Now I get this constantly:

```
time="2018-12-05T16:34:51Z" level=info msg="Cluster size needs reconciling: expected 3, has 0" cluster-name=nats pkg=cluster
time="2018-12-05T16:34:51Z" level=error msg="failed to reconcile: pods \"nats-1\" already exists" cluster-name=nats pkg=cluster
```

The describe on nats-1 (it's permanently terminated:
```
Name:           nats-1
Namespace:      nats-io
Node:           minikube/10.0.2.15
Start Time:     Wed, 05 Dec 2018 11:46:42 +0100
Labels:         app=nats
                nats_cluster=nats
                nats_version=1.3.0
Annotations:    nats.version=1.3.0
Status:         Failed
IP:             
Controlled By:  NatsCluster/nats
Containers:
  nats:
    Container ID:  docker://b0892b87b0ac1d25ff64e197a53e138b3e635f76f74589924d16eafa3a55d50e
    Image:         nats:1.3.0
    Image ID:      docker-pullable://nats@sha256:5e99caf7ca7b2e4a242e741328bde393bbd7a529a2cfdd19b84870da87ad6ca1
    Ports:         6222/TCP, 4222/TCP, 8222/TCP
    Command:
      /gnatsd
      -c
      /etc/nats-config/nats.conf
      -P
      /var/run/nats/gnatsd.pid
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 05 Dec 2018 11:46:49 +0100
      Finished:     Wed, 05 Dec 2018 17:22:54 +0100
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8222/ delay=10s timeout=10s period=60s #success=1 #failure=3
    Environment:
      SVC:    nats-mgmt
      EXTRA:  --http_port=8222
    Mounts:
      /etc/nats-config from nats-config (rw)
      /var/run/nats from pid (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pzlst (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  nats-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nats
    Optional:    false
  pid:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  default-token-pzlst:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pzlst
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

### PR DESCRIPTION
**Pull request by pires**
Fixes #104

This PR changes the reconciliation loop, so it deletes all pods that have reached a terminal state, i.e. phases `Failed` or `Succeeded`. This way, the operator can recover any pod which state is not supposed to be terminated.

### CODE REVIEW

File: pkg/cluster/cluster.go [hunk 1]
```diff
@@ -433,28 +441,34 @@ func (c *Cluster) pollPods() (running, pending []*v1.Pod, err error) {
...
 		case v1.PodRunning:
 			running = append(running, pod)
 		case v1.PodPending:
-			pending = append(pending, pod)
-		default:
-			c.logger.Warningf("ignoring pod %q with unexpected phase %q", pod.Name, pod.Status.Phase)
+			fallthrough
+		case v1.PodUnknown:
+			waiting = append(waiting, pod)
+		case v1.PodSucceeded:
```
Comment (wallyqs) [inline pkg/cluster/cluster.go]: ok this would mean that after lame duck exit 0 for example the operator would replace the pod as well

Comment (pires) [reply pkg/cluster/cluster.go]: No, it just deletes said pod. Only if the cluster size is greater than the number of pods, will a new one be provisioned.

Comment (wallyqs) [reply pkg/cluster/cluster.go]: can we punt deleting when COMPLETED/Succeeded for now? this means that pods that are terminated with `kubectl exec <pod> /gnatsd -sl=ldm=<pid>` would be replaced too by the operator, if so how can we delete the cluster pods with a graceful exit?

Comment (pires) [reply pkg/cluster/cluster.go]: My suggestion is enable LDM and scale the cluster to 0 before executing LDM.
